import FindDocMainStructure from "@/components/pages/FindADoctor/FindDocMainStructure";
import React from "react";

export const metadata = {
  title: "Get an Appointment | Unique Pathology",
  description: "Generated by create next app",
};

const GetAnAppointment = () => {
  return <FindDocMainStructure />;
};

export default GetAnAppointment;
