import React from "react";

export const metadata = {
  title: "Get an Appointment | Unique Pathology",
  description: "Generated by create next app",
};

const GetAnAppointmentPage = () => {
  return <div></div>;
};

export default GetAnAppointmentPage;
