import ContactUsMainStructure from "@/components/pages/ContactUs/ContactUsMainStructure";
import React from "react";

export const metadata = {
  title: "Contact Us | Unique HealthCare",
  description: "Generated by create next app",
};

const ContactUsPage = () => {
  return <ContactUsMainStructure />;
};

export default ContactUsPage;
