import React from "react";

export const metadata = {
  title: "Find a Doctor | Unique Pathology",
  description: "Generated by create next app",
};

const FindADoctorPage = () => {
  return <div></div>;
};

export default FindADoctorPage;
