import React from "react";

export const metadata = {
  title: "Our Pathology Lab | Unique HealthCare",
  description: "Generated by create next app",
};

const PathologyLabPage = () => {
  return <div></div>;
};

export default PathologyLabPage;
