import SignUpMainStructure from "@/components/pages/RegistrationPage/SignUpMainStructure";
import React from "react";

export const metadata = {
  title: "Register | Unique HealthCare",
  description: "Generated by create next app",
};

const RegisterPage = () => {
  return <SignUpMainStructure />;
};

export default RegisterPage;
