import { Inter } from "next/font/google";
import "./globals.scss";
import TanstackProvider from "@/providers/TanstackProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Unique Pathology",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackProvider>
          <main className="wrapper">{children}</main>
        </TanstackProvider>
      </body>
    </html>
  );
}
