import TanStackProvider from "@/providers/TanstackProvider";
import { Maven_Pro } from "next/font/google";
import NextUI from "@/providers/NextUI";
import "@/styles/globals.scss";
import NavigationBar from "@/components/common/NavigationBar";
import Footer from "@/components/common/Footer";

const MavenPro = Maven_Pro({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Unique Pathology",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light bg-accent">
      <body className={MavenPro.className}>
        <TanStackProvider>
          <NextUI>
            <NavigationBar />
            <main>{children}</main>
            <Footer />
          </NextUI>
        </TanStackProvider>
      </body>
    </html>
  );
}
