import React from "react";

export const metadata = {
  title: "Notice | Unique HealthCare",
  description: "Generated by create next app",
};

const NoticePage = () => {
  return <div></div>;
};

export default NoticePage;
