import LoginMainStructure from "@/components/pages/LoginPage/LoginMainStructure";
import React from "react";

export const metadata = {
  title: "Login | Unique HealthCare",
  description: "Generated by create next app",
};

const LoginPage = () => {
  return <LoginMainStructure />;
};

export default LoginPage;
