import ResetPassStructure from "@/components/pages/RecoverPassword/ResetPassStructure";
import React from "react";

export const metadata = {
  title: "Reset Password | Unique HealthCare",
  description: "Generated by create next app",
};

const ResetPasswordPage = () => {
  return <ResetPassStructure />;
};

export default ResetPasswordPage;
