import React from "react";

export const metadata = {
  title: "About Us | Unique HealthCare",
  description: "Generated by create next app",
};

const AboutUsPage = () => {
  return <div></div>;
};

export default AboutUsPage;
