import AboutUsMainStructure from "@/components/pages/AboutUs/AboutUsMainStructure";
import React from "react";

export const metadata = {
  title: "About Us | Unique HealthCare",
  description: "Generated by create next app",
};

const AboutUsPage = () => {
  return <AboutUsMainStructure />;
};

export default AboutUsPage;
